# Generated by Django 5.0.2 on 2024-02-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0002_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='product',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
