# Generated by Django 5.0.2 on 2024-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0003_home_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='product',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
