# Generated by Django 5.0.2 on 2024-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0004_alter_home_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getquote',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
