# Generated by Django 5.0.2 on 2024-02-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_app', '0005_alter_contact_phone_alter_getquote_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='product',
            new_name='text',
        ),
    ]
